[package]
name = "stealth_address_kit_example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stealth_address_kit = { path = "../sdk", default-features = false, features = ["secp256r1"] }
